### ISSUE TITLE
git sync fails when new files added

### ISSUE THREAD

**Issue by kitsonk** [phiggins42/rstwiki#20]
If a new file is added via the web interface, it doesn't get staged in the commit properly and therefore the push to GitHub fails.

**Comment by phiggins42** [comment]
There is a comment in the source ... something like "# should be git add [file] here too?" ... I suspect that is where it needs added.

**Comment by phiggins42** [comment]
https://github.com/phiggins42/rstwiki/blob/master/src/docserver.py#L162
