### ISSUE TITLE
Not In Cache - Request and Cache: http://api/rpc/1.8dojo/on

### ISSUE THREAD

**Issue by jk1420** [phiggins42/rstwiki#44]
When I try to  "sphinx-build -b html -d build/doctrees   source build/html 2> build/warnings.txt" , the console report the error as tile.

I the "baseUrl = "http://api/rpc/1.8dojo/on"" in src/dojo.py, I donnot know what it is meaing.

**Comment by kitsonk** [comment]
There are custom directives that link to the Dojo Toolkit API Docs.  Other than a warning, it simply will not inline the API documentation, otherwise you will need to install the [Dojo Toolkit API documentation](https://github.com/wkeese/api-viewer/) in a location and point the baseUrl at that.

**Comment by jk1420** [comment]
Thans for your repl, I has try to parse the dojo's source by the 《Dojo
Toolkit API documentation》's step, and get a error is "object true has no
method 'match'"

My system is win 7 64.

在 2013年7月19日星期五，Kitson Kelly notifications@github.com 写道：
